<?php
$data = array (
  6 => 
  array (
    'cat_id' => '6',
    'cat_name' => '家居用品',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '43',
    'level' => 0,
    'id' => '6',
    'name' => '家居用品',
  ),
  1 => 
  array (
    'cat_id' => '1',
    'cat_name' => '粮油土特产',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '5',
    'sort_order' => '60',
    'has_children' => '0',
    'goods_num' => '10',
    'level' => 0,
    'id' => '1',
    'name' => '粮油土特产',
  ),
  12 => 
  array (
    'cat_id' => '12',
    'cat_name' => '数码小家电',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '70',
    'has_children' => '0',
    'goods_num' => '35',
    'level' => 0,
    'id' => '12',
    'name' => '数码小家电',
  ),
  17 => 
  array (
    'cat_id' => '17',
    'cat_name' => '办公用品',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '80',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '17',
    'name' => '办公用品',
  ),
  16 => 
  array (
    'cat_id' => '16',
    'cat_name' => '创意礼品',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '90',
    'has_children' => '0',
    'goods_num' => '16',
    'level' => 0,
    'id' => '16',
    'name' => '创意礼品',
  ),
  18 => 
  array (
    'cat_id' => '18',
    'cat_name' => '定制礼品',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '100',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '18',
    'name' => '定制礼品',
  ),
);
?>